class PartnerRepository {}

// final response = [
//   {
//     "name": "Sarah Jenkins",
//     "company": "TechFlow Solutions",
//     "email": "sarah.j@techflow.io",
//     "phone": "+14155550192",
//     "location": "San Francisco, USA",
//     "status": "APPROVED",
//     "applied_date": "05/12/2025",
//   },
//   {
//     "name": "Arjun Mehta",
//     "company": "Global Logistics Corp",
//     "email": "arjun.mehta@globallog.com",
//     "phone": "+919876543210",
//     "location": "Mumbai, India",
//     "status": "PENDING",
//     "applied_date": "06/12/2025",
//   },
//   {
//     "name": "Elena Rodriguez",
//     "company": "Creative Minds Agency",
//     "email": "elena.rod@cminds.es",
//     "phone": "+34912345678",
//     "location": "Madrid, Spain",
//     "status": "REJECTED",
//     "applied_date": "07/12/2025",
//   },
//   {
//     "name": "Liam O'Connor",
//     "company": "Emerald Fintech",
//     "email": "liam.oc@emfin.ie",
//     "phone": "+35316329600",
//     "location": "Dublin, Ireland",
//     "status": "APPROVED",
//     "applied_date": "08/12/2025",
//   },
//   {
//     "name": "Yuki Tanaka",
//     "company": "Neo Tokyo Systems",
//     "email": "y.tanaka@neotokyo.jp",
//     "phone": "+81312345678",
//     "location": "Tokyo, Japan",
//     "status": "PENDING",
//     "applied_date": "09/12/2025",
//   },
//   {
//     "name": "Chloe Dupont",
//     "company": "Lumière Soft",
//     "email": "chloe.d@lumsoft.fr",
//     "phone": "+33140268521",
//     "location": "Paris, France",
//     "status": "APPROVED",
//     "applied_date": "10/12/2025",
//   },
//   {
//     "name": "David Smith",
//     "company": "Summit Peak Ventures",
//     "email": "d.smith@summitpeak.ca",
//     "phone": "+14165550101",
//     "location": "Toronto, Canada",
//     "status": "REJECTED",
//     "applied_date": "11/12/2025",
//   },
//   {
//     "name": "Amara Okafor",
//     "company": "Nile Digital",
//     "email": "a.okafor@niledigital.ng",
//     "phone": "+2348012345678",
//     "location": "Lagos, Nigeria",
//     "status": "APPROVED",
//     "applied_date": "12/12/2025",
//   },
//   {
//     "name": "Hans Müller",
//     "company": "Berlin Auto-Tech",
//     "email": "h.mueller@bautotech.de",
//     "phone": "+49301234567",
//     "location": "Berlin, Germany",
//     "status": "PENDING",
//     "applied_date": "13/12/2025",
//   },
//   {
//     "name": "Isabella Silva",
//     "company": "Amazonas Retail",
//     "email": "isabella.s@amazonas.br",
//     "phone": "+5511987654321",
//     "location": "São Paulo, Brazil",
//     "status": "APPROVED",
//     "applied_date": "14/12/2025",
//   },
//   {
//     "name": "Omar Al-Farsi",
//     "company": "Desert Sands Trading",
//     "email": "omar.f@desertsands.sa",
//     "phone": "+966112345678",
//     "location": "Riyadh, Saudi Arabia",
//     "status": "APPROVED",
//     "applied_date": "15/12/2025",
//   },
//   {
//     "name": "Zhang Wei",
//     "company": "Dragon Cloud Services",
//     "email": "wei.zhang@dragoncloud.cn",
//     "phone": "+861012345678",
//     "location": "Beijing, China",
//     "status": "PENDING",
//     "applied_date": "16/12/2025",
//   },
//   {
//     "name": "Sofia Rossi",
//     "company": "Veloce Designs",
//     "email": "s.rossi@veloce.it",
//     "phone": "+39061234567",
//     "location": "Milan, Italy",
//     "status": "REJECTED",
//     "applied_date": "17/12/2025",
//   },
//   {
//     "name": "James Wilson",
//     "company": "Blue Reef Consulting",
//     "email": "j.wilson@bluereef.au",
//     "phone": "+61298765432",
//     "location": "Sydney, Australia",
//     "status": "APPROVED",
//     "applied_date": "18/12/2025",
//   },
//   {
//     "name": "Fatima Zahra",
//     "company": "Atlas Innovations",
//     "email": "f.zahra@atlas.ma",
//     "phone": "+212522123456",
//     "location": "Casablanca, Morocco",
//     "status": "APPROVED",
//     "applied_date": "19/12/2025",
//   },
// ];
